convert to js with babel
NewSpring/react-storybook-addon-backgrounds pull request #34
Opened 2017-07-05 15:26 UTC by psimyn

seems to work
tests all pass

TODO
few packages have deprecation warnings and need updating
hundreds of lint errors (copied eslint config from storybook repo)

2017-07-05 23:02 UTC, psimyn commented on src/BackgroundPanel.js
> +      this.channel = this.props.channel;
`props.channel` is undefined on initial render. not sure why 😖

2017-07-06 19:01 UTC, ndelangen commented
Can you resolve the merge conflicts? 👍

2017-07-06 19:09 UTC, ndelangen requested changes

2017-07-06 19:09 UTC, ndelangen commented on package.json
> +    "eslint": "^3.19.0",
you're adding all these eslint dependencies but there's no lint script?

Looks like these rules are similar or the same as the main repo 👍

2017-07-06 19:09 UTC, ndelangen commented on package.json
> +    "babel-cli": "^6.24.1"
Is `babel-cli` a runtime dependency? If it's only required for build, it should be a devDependency?

2017-07-07 12:46 UTC, psimyn commented on package.json
> +    "eslint": "^3.19.0",
copied them from there, but there was hundreds of failing lints. I'll do the TS=>JS first then run prettier over it in another MR

2017-07-07 12:58 UTC, psimyn commented
@ndelangen updated and fixed 👍

2017-07-07 20:36 UTC, ndelangen approved these changes

2017-07-08 21:03 UTC, merged